name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of deployable artifact files
        required: false
        default: dist
        type: string
    #secrets:
    #  input-secret:
    #    required: false
    outputs:
      result:
        description: the result of deploy operation
        value: ${{ jobs.deploy-common.outputs.outcome }} # only supported for reusable workflows
jobs:
    deploy-common: 
        outputs:
          outcome: ${{ steps.output-step.outputs.my-result }}
        runs-on: ubuntu-latest
        steps: 
          - name: Get Code
            uses: actions/download-artifact@v3
            with: 
              name: ${{ inputs.artifact-name }}
          - name: List files
            run: ls 
          - name: Output Information
            run: echo "deploying & uploading.."
          - name: Set Output
            id: output-step
            run: echo "my-result=success" >> $GITHUB_OUTPUT
